"""empty message

Revision ID: 2e08fcd1b334
Revises:
Create Date: 2020-02-27 21:15:45.779832

"""
import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2e08fcd1b334"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchange",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "timestamp",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("exchange", sa.Integer(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["exchange"], ["exchange.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("timestamps")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "timestamps",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column(
            "stock_name", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
        sa.Column("price", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="timestamps_pkey"),
    )
    op.drop_table("timestamp")
    op.drop_table("exchange")
    # ### end Alembic commands ###
